from setuptools import setup, find_packages
setup(
  name = 'modulepy',
  packages = find_packages(),
  version = '0.9.2',
  license='MIT',
  description = 'Provides the utility of the module command from within python.',
  author = 'Tommi Kabelitz',
  author_email = 'tommi.kabelitz@gmail.com',
  url = 'https://github.com/TommiKabelitz',
  download_url = "https://github.com/TommiKabelitz/modulepy/archive/refs/tags/v0.9.2.tar.gz",
  keywords = ['Environment', 'Modules'],
  install_requires=[],
  classifiers=[
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Intended Audience :: Science/Research',
    'Topic :: Utilities',
    'License :: OSI Approved :: MIT License',
    'Operating System :: Unix',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',    
    'Programming Language :: Python :: 3.8',    
    'Programming Language :: Python :: 3.9',    
    'Programming Language :: Python :: 3.10',    
    'Programming Language :: Python :: 3.11',    
  ],
)
